model:
  # both api_base and api_key cannot be set at the same time. See how the model ChatOpenAI is instantiated in utils.
  api_base:
  api_key: placeholder
  deployment_name: mistralai/Mistral-7B-Instruct-v0.3
  api_type: openai # set to hit the local endpoint
  api_version: placeholder

embedding_model:
  api_base: placeholder
  api_key: placeholder
  deployment_name: pritamdeka/S-PubMedBert-MS-MARCO
  api_type: huggingface
  api_version: placeholder 

data:
  documents_dir: backpain_data_upgraded_ontology/papers/
  ontology_path: backpain_data_upgraded_ontology/ontology/high_level_ontology_no_defs.jsonld
  kg_storage_path: backpain_data_upgraded_ontology/high_level_ontology_no_defs/
  # index_dir: only used for kgrag
  subdir: False
  smart_pdf: True
  full_text: True
  chunk_size: 8192
  
query:
  method: ontohypergraph-rag-no-reasoning #kg-rag
  batch_size: 10
  mode: json
  questions_file: evaluation/questions/generated_questions_non_binary.json
  answers_file: evaluation/answers2/high_level_ontology_no_defs.json

question_generator:
  framework: ragas
  test_size: 10
  distr: 
    simple: 1.0
    reasoning: 0.0
    multi_context: 0.0 

evaluator:
  eval_file: results/news/ragas_answers.json
  reference_free: True
  type: single
  metrics: 
    - answer_correctness
    - faithfulness
    - answer_similarity
    - answer_relevancy
    - context_relevancy
    - context_precision
    - context_recall
    - context_entity_recall
